### ISSUE TITLE
support windows encode

### ISSUE THREAD

**Issue by wenna** [chmouel/ftp-cloudfs#50] opened 2013-07-16 07:36 UTC
I use command “ftp 172.18.56.235 2021” in Linux （swift proxy server also as ftpcloudserver ）
all the Chinese filename is messy code,like this 
ftp> cd 23
250 "/23" is the current directory.
ftp> ls
200 Active data connection established.
125 Data connection already open. Transfer starting.
-rw-r--r--   1 admin.admin admin.admin       71 Jul 15 18:39 ?????????.txt
-rw-r--r--   1 admin.admin admin.admin       19 Jul 15 19:44 ??????
-rw-r--r--   1 admin.admin admin.admin       37 Jul 15 22:05 ??????????????????.txt
226 Transfer complete.

but when I use swift command  ,It is normal.
root@ubuntu:~# swift  -A  http://172.18.200.23:5000/v2.0 -U admin:admin -K pass  -V 2 list 23
你好啊.txt
好好
新建文本文档.txt

also in windows .
I type the command "ftp://172.18.56.235:2021/"  in "my computer address bar  "  in windows  os
still  messy code like this
鏂板缓鏂囨湰鏂囨。.txt

I think may be the Windows use ansi code，and cloudftp use utf-8
but I want to use command "ftp://172.18.56.235:2021/" in windows address bar without  other ftp tools
How could I do this

**Comment by reidrac** [comment] 2013-07-16 08:08
I think this is a limitation with your client. pyftpdlib uses UTF-8 and that's what we support at the moment. The client should make any required translation.

In fact we have Chinese characters in a couple of tests (ie 汉语漢語) and it works fine, but our testing operating system local encoding is UTF-8.

I'll investigate this further because I may be wrong, but if I'm right... the problem is in the client.

**Comment by wenna** [comment] 2013-07-16 09:44
Chinese  can be display correctly when I use ftp tools, such as cyberduck.
You R right ,the problem is in the client.
but Our  demand is to type command "ftp://172.18.56.235:2021" directly in "my computer address bar" in windows  xp or windows 7
Windows default encode is GBK.
Could all this be  work ?
Many thanks.

**Comment by reidrac** [comment] 2013-07-16 10:13
I think this might be an error in pyftpdlib / windows explorer communication.

```
...
10:49:56    Command:    OPTS UTF8 ON
10:49:56    Response:   501 Invalid argument.
...
```

Looks like explorer expects a 200 response to that command or it won't use UTF-8, thus breaking the output. I can't confirm it because I don't have a Windows box at hand.

pyftpdlib is not supporting that OPTS command according to:

http://code.google.com/p/pyftpdlib/wiki/RFCsCompliance#RFC-2389_-_Feature_negotiation_mechanism_for_the_File_Transfer_P

I created a branch with a workaround implementing the "OPTS UTF8 ON" command: https://github.com/chmouel/ftp-cloudfs/tree/opts-utf8

Can you try it?

This is NOT a ftp-cloudfs bug but something that needs to be addressed in pyftpdlib. If this fixes your problem I'll file a bug report for pyftpdlib.

(I may need more details, like the exact windows version experiencing the problem, pyftpdlib version you're using, etc)

EDIT: typo

**Comment by wenna** [comment] 2013-07-16 10:37
pyftpdlib version is 1.2.0
I use windows xp Professional version  service pack 3 ,Chinese simplified---encode is GBK
and I am a java developer.I feel this hot potato for me.
I will  try doing it in my environment.

Just now
, use vsftp and type the command ftp://172.18.56.235:2021 in windows,the Chinese is correctly display.
something wrong with pyftpdlib.
Many thanks.

**Comment by reidrac** [comment] 2013-07-16 10:40
Excellent!

I will file a bug report in pyftpdlib. Meanwhile you can keep using the workaround.

**Closed as completed by reidrac** 2013-07-16 10:40 UTC

**Comment by reidrac** [comment] 2013-07-16 10:49
Done: http://code.google.com/p/pyftpdlib/issues/detail?id=266

**Comment by wenna** [comment] 2013-07-17 01:39
Thank you very much .After I add the  def ftp_OPTS(self, line) method ,it can display Chinese correctly in Windows Explorer client.
